In [3]:
#1

import numpy as np
from matplotlib import pyplot as plt


@np.vectorize
def f(c):
    return (c - 32) * (5/9)

temp_f = np.array([32, 68, 100, 212, 77])
temp_c = f(temp_f)
print([f"{x:.2f}" for x in temp_c])

ModuleNotFoundError: No module named 'matplotlib'

In [16]:
#2
@np.vectorize
def to_power(x, y):
    return np.power(x, y)

numbers = np.array([2, 3, 4, 5])
powers = np.array([1, 2, 3, 4])
result = to_power(numbers, powers)
print(result)

[  2   9  64 625]


$$
\begin{cases}
4x + 5y + 6z = 7 \\
3x - y + z = 4 \\
2x + y - 2z = 5
\end{cases}
$$

In [23]:
#3

#Coefficients
A = np.array([[4, 5, 6],
              [3, -1, 1],
              [2, 1, -2]])
#Constants
B = np.array([7, 4, 5])

solution = np.linalg.solve(A, B)
print(solution)

[ 1.7027027   0.62162162 -0.48648649]


$$
\begin{cases}
10I_1 - 2I_2 + 3I_3 = 12\\
-2I_1 + 8I_2 - I_3 = -5\\
3I_1 - I_2 + 6I_3 = 15
\end{cases}
$$

In [50]:
#4

#Coefficents
C = np.array([
    [10, -2, 3],
    [-2, 8, -1],
    [3, -1, 6]
])

#Constants
D = np.array([12, -5, 15])
solution2 = np.linalg.solve(C, D)
print(np.round(solution2, 2))

array([ 0.49, -0.23,  2.22])

In [83]:
#5
from PIL import Image

#5.1
#Flip function
def flip_img_(img):
    horizontal_flip = np.fliplr(img)
    vertical_flip = np.flipud(img)
    return horizontal_flip, vertical_flip

#5.2
#Add noise
def add_noise(img_array, noise_level=30):
    noise = np.random.randint(-noise_level, noise_level, img_array.shape, dtype=np.int16)
    noisy_image = img_array.astype(np.int16) + noise
    noisy_image = np.clip(noisy_image, 0, 255)
    return noisy_image.astype(np.uint8)

#5.3
#brigthen
def brighten_channel(img_array, channel=0, brightness=40):
    img_bright = img_array.copy()
    img_bright[..., channel] = np.clip(img_bright[..., channel] + brightness, 0, 255)
    return img_bright

#5.4
#apply mask
def apply_mask(img_array, mask_size=(100, 100)):
    img_masked = img_array.copy()
    h, w, _ = img_array.shape
    cx, cy = w // 2, h // 2  # Find center
    x1, y1 = cx - mask_size[0] // 2, cy - mask_size[1] // 2
    x2, y2 = x1 + mask_size[0], y1 + mask_size[1]
    img_masked[y1:y2, x1:x2] = (0, 0, 0)  # Set to black
    return img_masked

#orginal image
location = 'images/birds.jpg'
img = Image.open(location)
img_array = np.array(img)

#flipped ones
horizontal_flip, vertical_flip = flip_img_(img)

#added_noise
img_with_noise_array = add_noise(img_array, 40)

#brightened
bright_red = brighten_channel(img_array, channel=0, brightness=40)

#masked
masked_image = apply_mask(img_array)


#to save
Image.fromarray(horizontal_flip).save("images/horizontal_flip.jpg")
Image.fromarray(vertical_flip).save("images/vertical_flip.jpg")
Image.fromarray(img_with_noise_array).save("images/noisy_image.jpg")
Image.fromarray(bright_red).save("images/bright_red.jpg")
Image.fromarray(masked_image).save("images/masked_image.jpg")

#to show
Image.fromarray(horizontal_flip).show()
Image.fromarray(vertical_flip).show()
Image.fromarray(img_with_noise_array).show()
Image.fromarray(bright_red).show()
Image.fromarray(masked_image).show()


