import pandas as pd

In [ ]:
import pandas as pd
pd = pd.read_csv("TestMin.csv")



   Year2  Min1  Min2  Min3
0   2010    45    32    59
1   2011    41    62    28
2   2012    38    43    47
3   2013    51    37    39


In [6]:
import numpy as np
ar = np.random.randint(1, 100,size=[3,3])
print(ar)

[[62  6 91]
 [16 45 39]
 [48 19 12]]
